apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "blue-green-application-poc.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchExpressions:
    - key: {{ include "blue-green-application-poc.fullname" . }}
      operator: Exists

