apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "blue-green-application-poc.fullname" . }}
  labels:
    {{- include "blue-green-application-poc.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "MySecret"
          objectType: "secretsmanager"
