---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-echo
  namespace: http-echo
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-echo
  targetCPUUtilizationPercentage: 50

