apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: http-echo
  namespace: http-echo
spec:
  minAvailable: 1
  selector:
    matchExpressions:
    - key: http-echo
      operator: Exists

